### PR TITLE
Debounce overpass turbo requests

### PR DESCRIPTION
**Pull request by jakecoppinger**

### CODE REVIEW

**Comment by zlant** [comment]
5 second is a lot. I think enough 1-1.5 sec.  And cancel debounce on movestart event.

**Comment by jakecoppinger** [comment]
Good point, I'll reduce it to 1.5 seconds.

> And cancel debounce on movestart event.
Will do.

I didn't realise Lodash was already imported, I'll use that instead :)

**Comment by jakecoppinger** [comment]
Now using the lodash debounce and cancelling on movestart. Should be good to go!

**Comment by zlant** [comment]
Great!

**Pull request merged**
